const auth = require("../ControllerNew/adminController");
const { upload, FranchiseUpload, productUpload, brandUpload } = require('../middlewareNew/imageupload')
const authJwt = require("../middlewareNew/authJwt");
module.exports = (app) => {
        app.post("/api/v1/admin/registration", auth.registration);
        app.post("/api/v1/admin/signin", auth.signin);
        app.get("/api/v1/admin/getProfile", [authJwt.verifyToken], auth.getProfile);
        app.put("/api/v1/admin/changePassword", [authJwt.verifyToken], auth.changePassword);
        app.put("/api/v1/admin/updateProfile", [authJwt.verifyToken], upload.single('image'), auth.updateProfile);
        app.post("/api/v1/admin/createAboutUs", upload.single('image'), [authJwt.verifyToken], auth.createAboutUs);
        app.get("/api/v1/admin/getAllAboutUs", auth.getAllAboutUs);
        app.get("/api/v1/admin/getAboutUsById/:id", auth.getAboutUsById);
        app.delete("/api/v1/admin/deleteAboutUs/:id", [authJwt.verifyToken], auth.deleteAboutUs);
        app.put("/api/v1/admin/addUserinAboutUs", upload.single('image'), [authJwt.verifyToken], auth.addUserinAboutUs);
        app.delete("/api/v1/admin/deleteUserinAboutUs/:id", [authJwt.verifyToken], auth.deleteUserinAboutUs);
        app.post("/api/v1/ContactDetails/add", [authJwt.verifyToken], upload.single('image'), auth.addContactDetails);
        app.get("/api/v1/admin/ContactDetails/view", auth.viewContactDetails);
        app.post('/api/v1/static/createPrivacy', [authJwt.verifyToken], auth.createPrivacy);
        app.put('/api/v1/static/privacy/:id', [authJwt.verifyToken], auth.updatePrivacy);
        app.delete('/api/v1/static/privacy/:id', [authJwt.verifyToken], auth.deletePrivacy);
        app.get('/api/v1/static/getPrivacy', auth.getPrivacy);
        app.get('/api/v1/static/privacy/:id', auth.getPrivacybyId);
        app.post('/api/v1/static/createRefundPrivacy', [authJwt.verifyToken], auth.createRefundPrivacy);
        app.get('/api/v1/static/getRefundPrivacy', auth.getRefundPrivacy);
        app.post('/api/v1/static/createTerms', [authJwt.verifyToken], auth.createTerms);
        app.put('/api/v1/static/term/:id', [authJwt.verifyToken], auth.updateTerms);
        app.delete('/api/v1/static/term/:id', [authJwt.verifyToken], auth.deleteTerms);
        app.get('/api/v1/static/getTerm', auth.getTerms);
        app.get('/api/v1/static/term/:id', auth.getTermsbyId);
        app.post("/api/v1/static/faq/createFaq", authJwt.verifyToken, auth.createFaq);
        app.put("/api/v1/static/faq/:id", authJwt.verifyToken, auth.updateFaq);
        app.delete("/api/v1/static/faq/:id", authJwt.verifyToken, auth.deleteFaq);
        app.get("/api/v1/static/faq/All", auth.getAllFaqs);
        app.get("/api/v1/static/faq/:id", auth.getFaqById);
        app.post("/api/v1/admin/notification/sendNotification", authJwt.verifyToken, auth.sendNotification);
        app.get("/api/v1/admin/notification/allNotification", authJwt.verifyToken, auth.allNotification);
        app.get('/api/v1/admin/getOrder', [authJwt.verifyToken], auth.getOrder);
        app.put('/api/v1/admin/updateOrderStatus/:id', [authJwt.verifyToken], auth.updateOrderStatus);
        app.post("/api/v1/category/createCategory", [authJwt.verifyToken], upload.single('image'), auth.createCategory);
        app.get("/api/v1/category/allCategory", auth.getCategories);
        app.put("/api/v1/category/updateCategory/:id", [authJwt.verifyToken], upload.single('image'), auth.updateCategory);
        app.delete("/api/v1/category/removeCategory/:id", [authJwt.verifyToken], auth.removeCategory);
        app.get("/api/v1/category/getMainCategories", auth.getMainCategories);
        app.get("/api/v1/category/getFramesKartSmartSeriesCategories", auth.getFramesKartSmartSeriesCategories);
        app.get("/api/v1/category/getPremiumEyeWearCategories", auth.getPremiumEyeWearCategories);
        app.get("/api/v1/category/getPremiumLensCategories", auth.getPremiumLensCategories);
        app.get("/api/v1/category/getFramesKartSeriesCategories", auth.getFramesKartSeriesCategories);
        app.post("/api/v1/subcategory/createsubcategory", [authJwt.verifyToken], upload.single('image'), auth.createSubcategory);
        app.get("/api/v1/subcategory/allsubcategory", auth.getSubcategories);
        app.put("/api/v1/subcategory/updatesubcategory/:id", [authJwt.verifyToken], upload.single('image'), auth.updateSubcategory);
        app.delete("/api/v1/subcategory/removesubcategory/:id", [authJwt.verifyToken], auth.removeSubcategory);
        app.get("/api/v1/subcategory/subcategory/:categoryId", auth.getSubcategoryByCategory);
        app.post('/api/v1/banner', [authJwt.verifyToken], upload.single('image'), auth.AddBanner);
        app.get('/api/v1/banner', auth.getBanner);
        app.put('/api/v1/banner/updateBanner/:id', [authJwt.verifyToken], upload.single('image'), auth.updateBanner);
        app.delete('/api/v1/banner/:id', auth.removeBanner)
        app.get('/api/v1/banner/getBannerByType/:type', auth.getBannerByType);
        app.get('/api/v1/banner/getBannerBytryGlassesContactLens', auth.getBannerBytryGlassesContactLens);
        app.post("/api/v1/admin/RecommendeYoutube/addRecommendeYoutube", [authJwt.verifyToken], upload.single('image'), auth.createRecommendeYoutube);
        app.get("/api/v1/admin/RecommendeYoutube/allRecommendeYoutube", auth.getRecommendeYoutube);
        app.get("/api/v1/admin/RecommendeYoutube/getRecommendeYoutubeBytype/:type", auth.getRecommendeYoutubeBytype);
        app.put("/api/v1/admin/RecommendeYoutube/updateRecommendeYoutube/:id", [authJwt.verifyToken], upload.single('image'), auth.updateRecommendeYoutube);
        app.delete("/api/v1/admin/RecommendeYoutube/deleteRecommendeYoutube/:id", [authJwt.verifyToken], auth.removeRecommendeYoutube);
        app.post("/api/v1/brand/createBrand", brandUpload, [authJwt.verifyToken], auth.createBrand);
        app.get("/api/v1/brand/allBrand", auth.getBrand);
        app.put("/api/v1/brand/updateBrand/:id", brandUpload, [authJwt.verifyToken], auth.updateBrand);
        app.delete("/api/v1/brand/removeBrand/:id", [authJwt.verifyToken], auth.removeBrand)
        app.post("/api/v1/admin/FranchiseTestimonial/addFranchiseTestimonial", [authJwt.verifyToken], upload.single('image'), auth.createFranchiseTestimonial);
        app.get("/api/v1/admin/FranchiseTestimonial/allFranchiseTestimonial", auth.getFranchiseTestimonial);
        app.put("/api/v1/admin/FranchiseTestimonial/updateFranchiseTestimonial/:id", [authJwt.verifyToken], upload.single('image'), auth.updateFranchiseTestimonial);
        app.delete("/api/v1/admin/FranchiseTestimonial/deleteFranchiseTestimonial/:id", [authJwt.verifyToken], auth.removeFranchiseTestimonial);
        app.get("/api/v1/admin/getAllFranchiseInquiryData", auth.getAllFranchiseInquiryData);
        app.post("/api/v1/admin/addFranchise", FranchiseUpload, [authJwt.verifyToken], auth.addFranchise);
        app.get("/api/v1/admin/getFranchise", auth.getFranchise);
        app.get("/api/v1/admin/getFranchiseById/:id", auth.getFranchiseById);
        app.delete("/api/v1/admin/DeleteFranchise/:id", [authJwt.verifyToken], auth.DeleteFranchise);
        app.post("/api/v1/admin/createEyeTestCamp", upload.array('image'), [authJwt.verifyToken], auth.createEyeTestCamp);
        app.get("/api/v1/admin/getAllEyeTestCamp", auth.getAllEyeTestCamp);
        app.get("/api/v1/admin/getEyeTestCampById/:id", auth.getEyeTestCampById);
        app.delete("/api/v1/admin/deleteEyeTestCamp/:id", [authJwt.verifyToken], auth.deleteEyeTestCamp);
        app.get("/api/v1/admin/getAllEyeTestCampFormData", auth.getAllEyeTestCampFormData);
}
