const auth = require("../ControllerNew/adminController");
const { upload, FranchiseUpload, productUpload, brandUpload, guideUpload } = require('../middlewareNew/imageupload')
const authJwt = require("../middlewareNew/authJwt");
const visionTest = require("../ModelNew/visionTest/visionTest");
module.exports = (app) => {
        app.post("/api/v1/admin/registration", auth.registration);
        app.post("/api/v1/admin/signin", auth.signin);
        app.get("/api/v1/admin/getProfile", [authJwt.verifyToken], auth.getProfile);
        app.put("/api/v1/admin/changePassword", [authJwt.verifyToken], auth.changePassword);
        app.put("/api/v1/admin/updateProfile", [authJwt.verifyToken], upload.single('image'), auth.updateProfile);
        app.post("/api/v1/admin/createAboutUs", upload.single('image'), [authJwt.verifyToken], auth.createAboutUs);
        app.get("/api/v1/admin/getAllAboutUs", auth.getAllAboutUs);
        app.get("/api/v1/admin/getAboutUsById/:id", auth.getAboutUsById);
        app.delete("/api/v1/admin/deleteAboutUs/:id", [authJwt.verifyToken], auth.deleteAboutUs);
        app.put("/api/v1/admin/addUserinAboutUs", upload.single('image'), [authJwt.verifyToken], auth.addUserinAboutUs);
        app.delete("/api/v1/admin/deleteUserinAboutUs/:id", [authJwt.verifyToken], auth.deleteUserinAboutUs);
        app.post("/api/v1/ContactDetails/add", [authJwt.verifyToken], upload.single('image'), auth.addContactDetails);
        app.get("/api/v1/admin/ContactDetails/view", auth.viewContactDetails);
        app.post('/api/v1/static/createPrivacy', [authJwt.verifyToken], auth.createPrivacy);
        app.put('/api/v1/static/privacy/:id', [authJwt.verifyToken], auth.updatePrivacy);
        app.delete('/api/v1/static/privacy/:id', [authJwt.verifyToken], auth.deletePrivacy);
        app.get('/api/v1/static/getPrivacy', auth.getPrivacy);
        app.get('/api/v1/static/privacy/:id', auth.getPrivacybyId);
        app.post('/api/v1/static/createRefundPrivacy', [authJwt.verifyToken], auth.createRefundPrivacy);
        app.get('/api/v1/static/getRefundPrivacy', auth.getRefundPrivacy);
        app.post('/api/v1/static/createTerms', [authJwt.verifyToken], auth.createTerms);
        app.put('/api/v1/static/term/:id', [authJwt.verifyToken], auth.updateTerms);
        app.delete('/api/v1/static/term/:id', [authJwt.verifyToken], auth.deleteTerms);
        app.get('/api/v1/static/getTerm', auth.getTerms);
        app.get('/api/v1/static/term/:id', auth.getTermsbyId);
        app.post("/api/v1/static/faq/createFaq", authJwt.verifyToken, auth.createFaq);
        app.put("/api/v1/static/faq/:id", authJwt.verifyToken, auth.updateFaq);
        app.delete("/api/v1/static/faq/:id", authJwt.verifyToken, auth.deleteFaq);
        app.get("/api/v1/static/faq/All", auth.getAllFaqs);
        app.get("/api/v1/static/faq/:id", auth.getFaqById);
        app.post("/api/v1/admin/notification/sendNotification", authJwt.verifyToken, auth.sendNotification);
        app.get("/api/v1/admin/notification/allNotification", authJwt.verifyToken, auth.allNotification);
        app.get('/api/v1/admin/getOrder', [authJwt.verifyToken], auth.getOrder);
        app.put('/api/v1/admin/updateOrderStatus/:id', [authJwt.verifyToken], auth.updateOrderStatus);
        app.post("/api/v1/category/createCategory", [authJwt.verifyToken], upload.single('image'), auth.createCategory);
        app.get("/api/v1/category/allCategory", auth.getCategories);
        app.put("/api/v1/category/updateCategory/:id", [authJwt.verifyToken], upload.single('image'), auth.updateCategory);
        app.delete("/api/v1/category/removeCategory/:id", [authJwt.verifyToken], auth.removeCategory);
        app.get("/api/v1/category/getMainCategories", auth.getMainCategories);
        app.get("/api/v1/category/getFramesKartSmartSeriesCategories", auth.getFramesKartSmartSeriesCategories);
        app.get("/api/v1/category/getPremiumEyeWearCategories", auth.getPremiumEyeWearCategories);
        app.get("/api/v1/category/getPremiumLensCategories", auth.getPremiumLensCategories);
        app.get("/api/v1/category/getFramesKartSeriesCategories", auth.getFramesKartSeriesCategories);
        app.post("/api/v1/subcategory/createsubcategory", [authJwt.verifyToken], upload.single('image'), auth.createSubcategory);
        app.get("/api/v1/subcategory/allsubcategory", auth.getSubcategories);
        app.put("/api/v1/subcategory/updatesubcategory/:id", [authJwt.verifyToken], upload.single('image'), auth.updateSubcategory);
        app.delete("/api/v1/subcategory/removesubcategory/:id", [authJwt.verifyToken], auth.removeSubcategory);
        app.get("/api/v1/subcategory/subcategory/:categoryId", auth.getSubcategoryByCategory);
        app.post('/api/v1/banner', [authJwt.verifyToken], upload.single('image'), auth.AddBanner);
        app.get('/api/v1/banner', auth.getBanner);
        app.put('/api/v1/banner/updateBanner/:id', [authJwt.verifyToken], upload.single('image'), auth.updateBanner);
        app.delete('/api/v1/banner/:id', auth.removeBanner)
        app.get('/api/v1/banner/getBannerByType/:type', auth.getBannerByType);
        app.get('/api/v1/banner/getBannerBytryGlassesContactLens', auth.getBannerBytryGlassesContactLens);
        app.post("/api/v1/admin/RecommendeYoutube/addRecommendeYoutube", [authJwt.verifyToken], upload.single('image'), auth.createRecommendeYoutube);
        app.get("/api/v1/admin/RecommendeYoutube/allRecommendeYoutube", auth.getRecommendeYoutube);
        app.get("/api/v1/admin/RecommendeYoutube/getRecommendeYoutubeBytype/:type", auth.getRecommendeYoutubeBytype);
        app.put("/api/v1/admin/RecommendeYoutube/updateRecommendeYoutube/:id", [authJwt.verifyToken], upload.single('image'), auth.updateRecommendeYoutube);
        app.delete("/api/v1/admin/RecommendeYoutube/deleteRecommendeYoutube/:id", [authJwt.verifyToken], auth.removeRecommendeYoutube);
        app.post("/api/v1/brand/createBrand", brandUpload, [authJwt.verifyToken], auth.createBrand);
        app.get("/api/v1/brand/allBrand", auth.getBrand);
        app.put("/api/v1/brand/updateBrand/:id", brandUpload, [authJwt.verifyToken], auth.updateBrand);
        app.delete("/api/v1/brand/removeBrand/:id", [authJwt.verifyToken], auth.removeBrand)
        app.post("/api/v1/admin/FranchiseTestimonial/addFranchiseTestimonial", [authJwt.verifyToken], upload.single('image'), auth.createFranchiseTestimonial);
        app.get("/api/v1/admin/FranchiseTestimonial/allFranchiseTestimonial", auth.getFranchiseTestimonial);
        app.put("/api/v1/admin/FranchiseTestimonial/updateFranchiseTestimonial/:id", [authJwt.verifyToken], upload.single('image'), auth.updateFranchiseTestimonial);
        app.delete("/api/v1/admin/FranchiseTestimonial/deleteFranchiseTestimonial/:id", [authJwt.verifyToken], auth.removeFranchiseTestimonial);
        app.get("/api/v1/admin/getAllFranchiseInquiryData", auth.getAllFranchiseInquiryData);
        app.post("/api/v1/admin/addFranchise", FranchiseUpload, [authJwt.verifyToken], auth.addFranchise);
        app.get("/api/v1/admin/getFranchise", auth.getFranchise);
        app.get("/api/v1/admin/getFranchiseById/:id", auth.getFranchiseById);
        app.delete("/api/v1/admin/DeleteFranchise/:id", [authJwt.verifyToken], auth.DeleteFranchise);
        app.post("/api/v1/admin/createEyeTestCamp", upload.array('image'), [authJwt.verifyToken], auth.createEyeTestCamp);
        app.get("/api/v1/admin/getAllEyeTestCamp", auth.getAllEyeTestCamp);
        app.get("/api/v1/admin/getEyeTestCampById/:id", auth.getEyeTestCampById);
        app.delete("/api/v1/admin/deleteEyeTestCamp/:id", [authJwt.verifyToken], auth.deleteEyeTestCamp);
        app.get("/api/v1/admin/getAllEyeTestCampFormData", auth.getAllEyeTestCampFormData);
        app.post("/api/v1/admin/ColorGender/addColorGender", [authJwt.verifyToken],upload.single('image'), auth.createColorGender);
        app.get("/api/v1/admin/ColorGender/allColorGender", auth.getColorGender);
        app.get("/api/v1/admin/ColorGender/getColorGenderBytype/:type", auth.getColorGenderBytype);
        app.put("/api/v1/admin/ColorGender/updateColorGender/:id", [authJwt.verifyToken],upload.single('image'), auth.updateColorGender);
        app.delete("/api/v1/admin/ColorGender/deleteColorGender/:id", [authJwt.verifyToken], auth.removeColorGender);
        app.post("/api/v1/admin/Shape/addShape", [authJwt.verifyToken], upload.single('image'), auth.AddShape);
        app.get("/api/v1/admin/Shape/allShape", auth.getShape);
        app.put("/api/v1/admin/Shape/updateShape/:id", [authJwt.verifyToken], upload.single('image'), auth.updateShape);
        app.delete("/api/v1/admin/Shape/deleteShape/:id", [authJwt.verifyToken], auth.removeShape);
        app.post("/api/v1/admin/Style/AddStyle", [authJwt.verifyToken], upload.single('image'), auth.AddStyle);
        app.get("/api/v1/admin/Style/allStyle", auth.getStyle);
        app.put("/api/v1/admin/Style/updateStyle/:id", [authJwt.verifyToken], upload.single('image'), auth.updateStyle);
        app.delete("/api/v1/admin/Style/deleteStyle/:id", [authJwt.verifyToken], auth.removeStyle);
        app.delete("/api/v1/admin/deleteUser/:id", [authJwt.verifyToken], auth.deleteUser);
        app.get("/api/v1/admin/getuserById/:id", auth.getuserById);
        app.get("/api/v1/admin/getAlluser", auth.getAlluser);
        app.post("/api/v1/admin/addFcash/:id", [authJwt.verifyToken], auth.addFcash);
        app.post("/api/v1/admin/AddVisionTest", [authJwt.verifyToken], upload.single('image'), auth.AddVisionTest);
        app.get("/api/v1/admin/getAllVisionTest", auth.getVisionTest);
        app.put("/api/v1/admin/updateVisionTest/:id", [authJwt.verifyToken], upload.single('image'), auth.updateVisionTest);
        app.delete("/api/v1/admin/deleteVisionTest/:id", [authJwt.verifyToken], auth.removeVisionTest);
        app.put("/api/v1/admin/addInstructionInVisionTest/:visionTestId", upload.single('image'), [authJwt.verifyToken], auth.addInstructionInVisionTest);
        app.delete("/api/v1/admin/deleteInstructionInVisionTest/:id/:visionTestId", [authJwt.verifyToken], auth.deleteInstructionInVisionTest);
        app.post("/api/v1/admin/AddVisionTestQuestion/:visionTestId", [authJwt.verifyToken], upload.single('image'), auth.addQuestionInVisionTest);
        app.get("/api/v1/admin/getVisionTestQuestionById/:id", auth.getVisionTestQuestionById);
        app.put("/api/v1/admin/updateVisionTestQuestion/:id", [authJwt.verifyToken], upload.single('image'), auth.updateQuestionInVisionTest);
        app.get("/api/v1/admin/getAllVisionTestQuestion", auth.getQuestionInVisionTest);
        app.delete("/api/v1/admin/deleteVisionTestQuestion/:id", [authJwt.verifyToken], auth.removeQuestionInVisionTest);
        app.post("/api/v1/Subscription", auth.createSubscription);
        app.get("/api/v1/Subscription", auth.getAllSubscription);
        app.get("/api/v1/Subscription/byId/:id", auth.getSubscriptionById);
        app.put("/api/v1/Subscription/:id", auth.updateSubscription);
        app.delete("/api/v1/Subscription/:id", auth.deleteSubscription);
        app.post("/api/v1/guide/createGuide", guideUpload, [authJwt.verifyToken], auth.createGuide);
        app.get("/api/v1/guide/byId/:id", auth.getGuideById);
        app.put("/api/v1/guide/updateGuide/:id", guideUpload, [authJwt.verifyToken], auth.updateGuide);
        app.get("/api/v1/guide/allGuide", auth.getGuide);
        app.delete("/api/v1/guide/removeGuide/:id", [authJwt.verifyToken], auth.removeGuide)
        app.post("/api/v1/guide/addQuestionInGuide/:guideId", [authJwt.verifyToken], upload.single('image'), auth.createQuestionInGuide);
        app.get("/api/v1/guide/getQuestionInGuideById/:id", auth.getQuestionInGuideById);
        app.put("/api/v1/guide/updateQuestionInGuide/:id", [authJwt.verifyToken], upload.single('image'), auth.updateQuestionInGuide);
        app.get("/api/v1/guide/getAllQuestionInGuide/:guideId", auth.getQuestionInGuide);
        app.delete("/api/v1/guide/deleteQuestionInGuide/:id", [authJwt.verifyToken], auth.deleteQuestionInGuide);
        app.post('/api/v1/offer', [authJwt.verifyToken], upload.single('image'), auth.AddOffer);
        app.get('/api/v1/offer', auth.getOffer);
        app.put('/api/v1/offer/updateOffer/:id', [authJwt.verifyToken], upload.single('image'), auth.updateOffer);
        app.delete('/api/v1/offer/:id', auth.removeOffer);
        app.post("/api/v1/lens/createPowerTypeCategory", [authJwt.verifyToken], upload.single('image'), auth.createPowerTypeCategory);
        app.get("/api/v1/lens/allPowerTypeCategory", auth.getPowerTypeCategories);
        app.put("/api/v1/lens/updatePowerTypeCategory/:id", [authJwt.verifyToken], upload.single('image'), auth.updatePowerTypeCategory);
        app.delete("/api/v1/lens/removePowerTypeCategory/:id", [authJwt.verifyToken], auth.removePowerTypeCategory);
        app.post("/api/v1/lens/createPowerTypeSubcategory", [authJwt.verifyToken], upload.single('image'), auth.createPowerTypeSubcategory);
        app.get("/api/v1/lens/allsubcategory", auth.getPowerTypeSubcategories);
        app.put("/api/v1/lens/updatesubcategory/:id", [authJwt.verifyToken], upload.single('image'), auth.updatePowerTypeSubcategory);
        app.delete("/api/v1/lens/removesubcategory/:id", [authJwt.verifyToken], auth.removePowerTypeSubcategory);
        app.get("/api/v1/lens/subcategory/:categoryId", auth.getPowerTypeSubcategoryByCategory);
        app.post("/api/v1/admin/Frame/AddFrame", [authJwt.verifyToken], upload.single('image'), auth.AddFrame);
        app.get("/api/v1/admin/Frame/allFrame", auth.getFrame);
        app.put("/api/v1/admin/Frame/updateFrame/:id", [authJwt.verifyToken], upload.single('image'), auth.updateFrame);
        app.delete("/api/v1/admin/Frame/deleteFrame/:id", [authJwt.verifyToken], auth.removeFrame);
        app.post("/api/v1/lens/createLens", [authJwt.verifyToken], upload.single('image'), auth.createLens);
        app.get("/api/v1/lens/allLens", auth.getLens);
        app.put("/api/v1/lens/updateLens/:lensId", [authJwt.verifyToken], upload.single('image'), auth.updateLens);
        app.delete("/api/v1/lens/deleteLens/:id", [authJwt.verifyToken], auth.removeLens);        
        app.post("/api/v1/admin/accessories/createAccessories", [authJwt.verifyToken], upload.single('image'), auth.createAccessories);
        app.get("/api/v1/admin/accessories/allAccessories", auth.getAccessories);
        app.put("/api/v1/admin/accessories/updateAccessories/:id", [authJwt.verifyToken], upload.single('image'), auth.updateAccessories);
        app.delete("/api/v1/admin/accessories/removeAccessories/:id", [authJwt.verifyToken], auth.removeAccessories);
        app.post("/api/v1/admin/createBreakageCoverage", upload.single('image'), [authJwt.verifyToken], auth.createBreakageCoverage);
        app.get("/api/v1/admin/getBreakageCoverage", auth.getBreakageCoverage);
        app.delete("/api/v1/admin/deleteBreakageCoverage/:id", [authJwt.verifyToken], auth.deleteBreakageCoverage);
        app.post("/api/v1/admin/createProduct", productUpload, [authJwt.verifyToken], auth.createProduct);
        app.get("/api/v1/admin/getProducts", auth.getProducts);
        app.get("/api/v1/admin/getProductsbyid/:id", auth.getProductDetails);
        app.delete("/api/v1/admin/deleteProducts/:id", [authJwt.verifyToken], auth.deleteProducts);
        app.post("/api/v1/admin/createBottomCard", upload.single('image'), [authJwt.verifyToken], auth.createBottomCard);
        app.get("/api/v1/admin/getBottomCard", auth.getBottomCard);
        app.delete("/api/v1/admin/deleteBottomCard/:id", [authJwt.verifyToken], auth.deleteBottomCard);  
        app.post("/api/v1/admin/createPremiumLenses", upload.single('image'), [authJwt.verifyToken], auth.createPremiumLenses);
        app.get("/api/v1/admin/getAllPremiumLenses", auth.getAllPremiumLenses);
        app.get("/api/v1/admin/getPremiumLensesById/:id", auth.getPremiumLensesById);
        app.delete("/api/v1/admin/deletePremiumLenses/:id", [authJwt.verifyToken], auth.deletePremiumLenses);
        app.post("/api/v1/admin/Store/addStore", [authJwt.verifyToken], upload.single('image'), auth.addStore);
        app.get("/api/v1/admin/listStore", auth.listStore);
        app.get("/api/v1/admin/viewStore/:id", auth.viewStore);
        app.put("/api/v1/admin/Store/editStore/:id", [authJwt.verifyToken], upload.single('image'), auth.editStore);
        app.delete("/api/v1/admin/deleteStore/:id", [authJwt.verifyToken], auth.deleteStore);
}
